'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Github, Key, FolderGit2, X, Loader2, CheckCircle, AlertCircle } from 'lucide-react';
import { Octokit } from 'octokit';
import { GeneratedFile } from '@/lib/gemini';
import { cn } from '@/lib/utils';

interface GitHubModalProps {
  isOpen: boolean;
  onClose: () => void;
  files: GeneratedFile[];
  projectName: string;
}

export const GitHubModal: React.FC<GitHubModalProps> = ({ isOpen, onClose, files, projectName }) => {
  const [token, setToken] = useState('');
  const [repoName, setRepoName] = useState(projectName.toLowerCase().replace(/\s+/g, '-'));
  const [isPrivate, setIsPrivate] = useState(false);
  const [createPR, setCreatePR] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [status, setStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [message, setMessage] = useState('');
  const [repoUrl, setRepoUrl] = useState('');
  const [prUrl, setPrUrl] = useState('');

  const [tokenError, setTokenError] = useState('');

  const validateToken = (value: string) => {
    if (!value) {
      setTokenError('Token is required');
      return false;
    }
    if (!value.startsWith('ghp_') && !value.startsWith('github_pat_')) {
      setTokenError('Token usually starts with "ghp_" or "github_pat_"');
      // We don't block submission, just warn
    } else {
      setTokenError('');
    }
    return true;
  };

  const handlePush = async () => {
    if (!validateToken(token) || !repoName) return;

    setIsLoading(true);
    setStatus('idle');
    setMessage('');

    try {
      const octokit = new Octokit({ auth: token });

      // 1. Get User Info
      const { data: user } = await octokit.rest.users.getAuthenticated();

      // 2. Create Repo (or get existing)
      let repo;
      try {
        const { data } = await octokit.rest.repos.createForAuthenticatedUser({
          name: repoName,
          private: isPrivate,
          auto_init: true, // Initialize with README to allow commits
        });
        repo = data;
      } catch (e: any) {
        if (e.status === 422) {
          // Repo exists, get it
          const { data } = await octokit.rest.repos.get({
            owner: user.login,
            repo: repoName,
          });
          repo = data;
        } else {
          throw e;
        }
      }

      // 3. Get default branch ref
      const { data: ref } = await octokit.rest.git.getRef({
        owner: user.login,
        repo: repoName,
        ref: `heads/${repo.default_branch}`,
      });
      const latestCommitSha = ref.object.sha;

      // 4. Create Blobs & Tree
      const treeItems = await Promise.all(files.map(async (file) => {
        const { data: blob } = await octokit.rest.git.createBlob({
          owner: user.login,
          repo: repoName,
          content: file.content,
          encoding: 'utf-8',
        });
        return {
          path: file.path,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blob.sha,
        };
      }));

      const { data: tree } = await octokit.rest.git.createTree({
        owner: user.login,
        repo: repoName,
        base_tree: latestCommitSha,
        tree: treeItems,
      });

      // 5. Create Commit
      const { data: commit } = await octokit.rest.git.createCommit({
        owner: user.login,
        repo: repoName,
        message: 'Update from TechWiser AI',
        tree: tree.sha,
        parents: [latestCommitSha],
      });

      if (createPR) {
        // Create a new branch
        const branchName = `techwiser-update-${Date.now()}`;
        await octokit.rest.git.createRef({
          owner: user.login,
          repo: repoName,
          ref: `refs/heads/${branchName}`,
          sha: commit.sha,
        });

        // Create PR
        const { data: pr } = await octokit.rest.pulls.create({
          owner: user.login,
          repo: repoName,
          title: 'Update from TechWiser AI',
          head: branchName,
          base: repo.default_branch,
          body: 'This PR was automatically generated by TechWiser AI.',
        });

        setStatus('success');
        setMessage('Successfully created Pull Request!');
        setRepoUrl(repo.html_url);
        setPrUrl(pr.html_url);
      } else {
        // 6. Update Ref (Direct Push)
        await octokit.rest.git.updateRef({
          owner: user.login,
          repo: repoName,
          ref: `heads/${repo.default_branch}`,
          sha: commit.sha,
        });

        setStatus('success');
        setMessage('Successfully pushed to GitHub!');
        setRepoUrl(repo.html_url);
      }
    } catch (error: any) {
      console.error('GitHub Push Error:', error);
      setStatus('error');

      let errorMessage = error.message || 'Failed to push to GitHub';
      if (errorMessage.includes('Resource not accessible by personal access token') || error.status === 403) {
        errorMessage = 'Token lacks required permissions. Please generate a Classic Token with "repo" scope, or ensure your Fine-grained token has "Administration" & "Contents" Write access to All Repositories.';
      }

      setMessage(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
          />

          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="relative w-full max-w-md glass-panel rounded-2xl border border-white/10 shadow-2xl overflow-hidden bg-[#0d1117]"
          >
            <div className="p-6 space-y-6">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-white/5 rounded-xl border border-white/10">
                    <Github size={20} className="text-white" />
                  </div>
                  <h2 className="text-lg font-bold">Push to GitHub</h2>
                </div>
                <button onClick={onClose} className="p-2 hover:bg-white/5 rounded-lg text-white/40 hover:text-white transition-colors">
                  <X size={18} />
                </button>
              </div>

              {status === 'success' ? (
                <div className="flex flex-col items-center justify-center py-8 space-y-4 text-center">
                  <div className="w-16 h-16 rounded-full bg-emerald-500/10 flex items-center justify-center border border-emerald-500/20">
                    <CheckCircle size={32} className="text-emerald-500" />
                  </div>
                  <div className="space-y-1">
                    <h3 className="text-lg font-bold text-white">Success!</h3>
                    <p className="text-sm text-white/60">{createPR ? 'Pull Request created successfully.' : 'Your code has been pushed to the repository.'}</p>
                  </div>
                  <div className="flex gap-2">
                    <a
                      href={repoUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="px-6 py-2 bg-white text-black font-bold rounded-xl hover:bg-white/90 transition-colors flex items-center gap-2 text-sm"
                    >
                      View Repository <FolderGit2 size={14} />
                    </a>
                    {prUrl && (
                      <a
                        href={prUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="px-6 py-2 bg-emerald-500 text-black font-bold rounded-xl hover:bg-emerald-400 transition-colors flex items-center gap-2 text-sm"
                      >
                        View PR <Github size={14} />
                      </a>
                    )}
                  </div>
                </div>
              ) : (
                <div className="space-y-4">
                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase tracking-wider text-white/40">Personal Access Token</label>
                    <div className="relative">
                      <Key size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/30" />
                      <input
                        type="password"
                        value={token}
                        onChange={(e) => {
                          setToken(e.target.value);
                          if (tokenError) setTokenError('');
                        }}
                        onBlur={(e) => validateToken(e.target.value)}
                        placeholder="ghp_..."
                        className={cn(
                          "w-full bg-black/20 border rounded-xl py-2.5 pl-9 pr-4 text-sm text-white placeholder:text-white/20 focus:outline-none transition-colors",
                          tokenError
                            ? "border-red-500/50 focus:border-red-500"
                            : "border-white/10 focus:border-emerald-500/50"
                        )}
                      />
                    </div>
                    {tokenError && (
                      <p className="text-[10px] text-red-400 font-medium flex items-center gap-1">
                        <AlertCircle size={10} /> {tokenError}
                      </p>
                    )}
                    <p className="text-[10px] text-white/30 mt-2">
                      Recommended: <a href="https://github.com/settings/tokens/new?description=TechWiser+AI+Builder&scopes=repo,workflow" target="_blank" rel="noreferrer" className="text-emerald-500 hover:underline">Generate Classic Token</a> (with <code className="bg-white/10 px-1 rounded">repo</code> scope).
                      <br />
                      <span className="opacity-75 tracking-tight">For Fine-grained tokens, grant "Administration" & "Contents" Write access to All Repositories.</span>
                    </p>
                  </div>

                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase tracking-wider text-white/40">Repository Name</label>
                    <div className="relative">
                      <FolderGit2 size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/30" />
                      <input
                        type="text"
                        value={repoName}
                        onChange={(e) => setRepoName(e.target.value)}
                        placeholder="my-awesome-project"
                        className="w-full bg-black/20 border border-white/10 rounded-xl py-2.5 pl-9 pr-4 text-sm text-white placeholder:text-white/20 focus:outline-none focus:border-emerald-500/50 transition-colors"
                      />
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="private-repo"
                      checked={isPrivate}
                      onChange={(e) => setIsPrivate(e.target.checked)}
                      className="rounded border-white/10 bg-white/5 text-emerald-500 focus:ring-emerald-500/50"
                    />
                    <label htmlFor="private-repo" className="text-sm text-white/60 select-none cursor-pointer">Private Repository</label>
                  </div>

                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="create-pr"
                      checked={createPR}
                      onChange={(e) => setCreatePR(e.target.checked)}
                      className="rounded border-white/10 bg-white/5 text-emerald-500 focus:ring-emerald-500/50"
                    />
                    <label htmlFor="create-pr" className="text-sm text-white/60 select-none cursor-pointer">Create Pull Request</label>
                  </div>

                  {status === 'error' && (
                    <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/20 flex items-start gap-2 text-red-400 text-xs">
                      <AlertCircle size={14} className="mt-0.5 shrink-0" />
                      <span>{message}</span>
                    </div>
                  )}

                  <button
                    onClick={handlePush}
                    disabled={isLoading || !token || !repoName}
                    className="w-full py-3 bg-[#238636] hover:bg-[#2ea043] disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg shadow-emerald-900/20"
                  >
                    {isLoading ? <Loader2 size={16} className="animate-spin" /> : <Github size={16} />}
                    {isLoading ? 'Pushing...' : (createPR ? 'Create Pull Request' : 'Push to GitHub')}
                  </button>
                </div>
              )}
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
